version: '3.8'
services:


  notificacion:
    build:
      context: .
      dockerfile: Subasta-notificacion/Subasta-notificacion/Dockerfile-notificacion
    ports:
      - "8082:8082"
    networks:
      - subasta-net
    volumes:
      - ~/.m2:/root/.m2





  subasta-producto:
    build:
      context: .
      dockerfile: Subasta-producto/Subasta-producto/Dockerfile-producto
    ports:
      - "8083:8083"
    networks:
      - subasta-net
    volumes:
      - ~/.m2:/root/.m2



  subasta-puja:
    build:
      context: .
      dockerfile: Subasta-puja/Subasta-puja/Dockerfile-puja
    ports:
      - "8084:8084"
    networks:
      - subasta-net
    volumes:
      - ~/.m2:/root/.m2




  subasta-service:
    build:
      context: .
      dockerfile: Subasta-service/Subasta-service/Dockerfile-service
    ports:
      - "8085:8085"
    networks:
      - subasta-net
    volumes:
      - ~/.m2:/root/.m2






  subasta-historial:
    build:
      context: .
      dockerfile: Subasta-historial/Subasta-historial/Dockerfile-historial
    container_name: subasta-historial
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8081:8081"
    networks:
      - subasta-net





  api-gateway:
    build:
      context: .
      dockerfile: Subasta-gateway/Subasta-gateway/Dockerfile-gateway
    container_name: api-gateway
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    networks:
      - subasta-net




  eureka-server:
    build:
      context: .
      dockerfile: Subasta-eureka/Subasta-eureka/Dockerfile-eureka
    ports:
      - "8761:8761"
    networks:
      - subasta-net
    volumes:
      - ~/.m2:/root/.m2


networks:
    subasta-net:
      driver: bridge



