
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /build
COPY ../.. .
RUN mvn -B -ntp clean package -DskipTests -pl Subasta-puja/Subasta-puja -am


FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /build/Subasta-puja/Subasta-puja/target/*.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]
