


FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /build
COPY ../.. .
RUN mvn -B -ntp clean package -DskipTests -pl Subasta-eureka/Subasta-eureka -am


FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /build/Subasta-eureka/Subasta-eureka/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]
